# Generated by Django 6.0.2 on 2026-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='food_item',
            new_name='food',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
